# import = ["/home/jk/.config/alacritty/catppuccin/catppuccin_latte.toml"]
import = ["/home/jk/.config/alacritty/catppuccin/catppuccin_mocha.toml"]

# shell = "/usr/bin/nu"
shell = "/usr/bin/fish"

# [shell]
# program = "/home/jk/.cargo/bin/zellij"
# args = ["-l", "welcome"]

[font]
size = 12

[font.normal]
family = "Hack Nerd Font Mono"
style = "Retina"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "PageUp"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "PageDown"
